# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJgPDxpDduD7Q5e7FScsZBZrbeUMKBGm
"""

# 1
l=float(input("Enter the length of rectangle "))
b=float(input("Enter the breadth of rectangle "))
print("Area of rectangle is:",l*b)

# 2
h=float(input("Enter your height in meters "))
w=float(input("Enter your weight in kilograms "))
print("Your BMI is:",w/(h**2))

# 3
student_scores = {}
no = int(input("Enter the number of students: "))
for i in range(no):
    name = input("Enter student name: ")
    score = float(input("Enter student score: "))
    student_scores[name] = score
print("\nStudent names and scores:")
for name, score in student_scores.items():
    print(f"{name}: {score}")

# 4
age = int(input("Enter your age: "))
if age<18:
    print("You are a minor")
elif age<=55:
    print("You are an adult")
else:
    print("You are a senior")

# 5
for i in range(2,51,2):
  print(i)

# 6
correct_pass='abc@123'
while True:
    pass_input = input("Enter the password: ")
    if pass_input == correct_pass:
        print("Correct password entered!")
        break  # Exit the loop if correct password
    else:
        print("Incorrect password! Please try again.")

# 7
def calc_average(numbers):
    if len(numbers) == 0:
        return 0
    return sum(numbers)/len(numbers)

num_list = [1, 2, 3, 4, 5]
avg = calc_average(num_list)
print("Average:", avg)

# 8
def count_vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

input_string = "Hi My name is Sankalp"
vowel_count = count_vowels(input_string)
print("Number of vowels:", vowel_count)

# 9
import datetime
print("Current date:", datetime.date.today())
print("Current time:", datetime.datetime.now().time())

# 10
def add_n(num1, num2):
    try:
        result = float(num1) + float(num2)  # Convert inputs to numbers and add them
        return result
    except ValueError:
        return "Non-numeric input is present."

num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")
sum = add_n(num1, num2)
print("Sum:", sum)

# 11
while True:
  try:
    num = int(input("Enter an integer: "))
    break
  except ValueError:
    print("Error: Please enter an integer value.")
print("You entered:", num)

# 12
def divide_n(num1, num2):
    try:
        result = num1 / num2
        return result
    except ZeroDivisionError:
        return "Error: Division by zero error."

dividend = float(input("Enter the dividend: "))
divisor = float(input("Enter the divisor: "))

ans = divide_n(dividend, divisor)
print("Division result:", ans)

# 13
text = "Hello, Python!"
new_file = open("new_file.txt", "w")
new_file.write(text)
new_file.close()
print("Successfully created and wrote to hello.txt.")

# 14
read_file = open("new_file.txt", "r")
print("Contents of the created file:")
print(read_file.read())
read_file.close()

append_file = open("new_file.txt", "a")
append_file.write("\nHi, my name is Sankalp.")
append_file.close()

read_file = open("new_file.txt", "r")
print("Contents of the created file:")
print(read_file.read())
read_file.close()